version: "3.8"
services:
  datanode:
    build:
      context: .
      dockerfile: ./datanode/Dockerfile
    command: python main.py
    env_file:
      - datanode/.env
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./datanode:/app
      - ./protos:/app/protos


